export const LANDING_PAGE = {
  SEQUENCE: [
    "Hi! I am Syamantak",
    2000,
    "Hi! I am a Full Stack Developer",
    2000,
    "Hi! I Build Digital Experiences",
    2000,
  ],
  SUBTITLE: "Let's code your way online",
  CTA_BUTTON: "View My Work",
};

export const CONTACT_PAGE = {
  HEADING: "GET IN TOUCH",
  SUBHEADING_1: "Let's build something ",
  SUBHEADING_HIGHLIGHT: "extraordinary",
  SUBHEADING_2: " together.",
  DESCRIPTION: "Whether you have a question, a project idea, or just want to say hi, my inbox is always open.",
  EMAIL: "srkr.9298@gmail.com",
  FORM: {
    NAME_LABEL: "Full Name",
    NAME_PLACEHOLDER: "John Doe",
    EMAIL_LABEL: "Email Address",
    EMAIL_PLACEHOLDER: "john@example.com",
    MESSAGE_LABEL: "Message",
    MESSAGE_PLACEHOLDER: "Tell me about your project...",
    SUBMIT_BUTTON: "Send Message",
    SUBMITTING_BUTTON: "Sending...",
    ERROR_MISSING_DETAILS: "Please enter all details",
    ERROR_INVALID_EMAIL: "Please enter a valid email",
    SUCCESS_MESSAGE: "Message sent successfully!",
    ERROR_SENDING: "Failed to send message.",
    ERROR_GENERAL: "An error occurred.",
  },
  FOOTER: "Made by Syamantak Sarkar. All rights reserved.",
};

export const SECTION_HEADINGS = {
  EXPERIENCE: "EXPERIENCE",
  PROJECTS: "PROJECTS",
  SKILLS: "TECHNICAL TOOLS",
  CERTIFICATIONS: "CERTIFICATIONS",
};

export const NAVBAR_LABELS = {
  HOME: "Home",
  EXPERIENCE: "Experience",
  SKILLS: "Skills",
  PROJECTS: "Projects",
  CONTACT: "Contact"
};

export const NAVBAR_IDS = {
  HOME: "home",
  EXPERIENCE: "experience",
  SKILLS: "skills",
  PROJECTS: "projects",
  CONTACT: "contact"
};

export const NAVBAR_MENUS = [
  { label: NAVBAR_LABELS.HOME, id: NAVBAR_IDS.HOME },
  { label: NAVBAR_LABELS.EXPERIENCE, id: NAVBAR_IDS.EXPERIENCE },
  { label: NAVBAR_LABELS.SKILLS, id: NAVBAR_IDS.SKILLS },
  { label: NAVBAR_LABELS.PROJECTS, id: NAVBAR_IDS.PROJECTS },
  { label: NAVBAR_LABELS.CONTACT, id: NAVBAR_IDS.CONTACT },
];

export const META_TAGS = {
  TITLE: "Syamantak Sarkar",
  DESCRIPTION: "Generated by create next app",
};
